<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Ocelot.Testing" Version="25.0.0-beta.9" />
    <PackageReference Include="TestStack.BDDfy.Xunit" Version="3.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <!-- Conditionally obtain references for the .NET 8.0 target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.27" />
  </ItemGroup>
  <!-- Conditionally obtain references for the .NET 9.0 target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.16" />
  </ItemGroup>
  <!-- Conditionally obtain references for the .NET 10.0 target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Ocelot.Cache.CacheManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Moq" />
    <Using Include="Xunit" />
    <Using Include="Ocelot.Cache" />
    <Using Include="Ocelot.Cache.CacheManager" />
  </ItemGroup>

</Project>
